name: design_note
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  gap: ^3.0.1
  intersperse: ^2.0.0
  material_symbols_icons: ^4.2719.3
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
